### ISSUE TITLE
particles.scm

### ISSUE THREAD

**Issue by Negdayen** [AlexCharlton/glls#13]
I think I should be seeing stuff, but it's just a blank black window; tested under Ubuntu and Windows with the same results using csc and csi.

**Comment by AlexCharlton** [comment]
This could be a matter of your drivers not supporting glsl version 130 (at least not with how the context is set up). Removing the version number from the vertex and fragment shader will fix the problem in this case.

**Comment by Negdayen** [comment]
Deleting the version declarations had no effect on either platform. But yeah, it was a context issue.

```
--- particles.scm	2016-05-08 06:30:55 -0700
+++ ../../glls-new/examples/particles.scm	2016-05-08 21:06:45 -0700
@@ -72,7 +72,7 @@
 ;;; Run in a thread so that you can still use the REPL
 (thread-start!
  (lambda ()
-   (glfw:with-window (640 480 "Example" resizable: #f)
+   (glfw:with-window (640 480 "Example" resizable: #f context-version-major: 3 opengl-forward-compat: #t)
      (gl:init)
 
      (gl:enable gl:+vertex-program-point-size+)
```

The above patch produced a working program in Ubuntu. However, it seems to have led me to something that seems a bit more insidious in Windows.

`interactive.scm` gets stuck in the repl; the rendering thread is only given time to run when an arbitrary expression is entered in the repl. IE, at first an empty window pops up, and after inputting a few arbitrary expression into the repl, the graphic appears.

In the case of particle.scm, I get semi-stuck in `move-points-randomly`, processing maybe 50 vertices per input expression.

Not sure what can be done about it, if anything. I'm guessing it probably has to do with how the csi repl is implemented on Windows?

**Comment by AlexCharlton** [comment]
I take it the context provided by Hypergiant allows you to run its particles example?

I think you're right in suspecting that something's going on with how the repl works in Windows. While the Chicken implementers maybe be interested in that, I'm afraid it's too far out of my scope!

**Comment by Negdayen** [comment]
Yes, Hypergiant's particle.scm ran without modification.

**Comment by AlexCharlton** [comment]
So to summarize: this is an issue with Chicken's interpreter on windows. While unfortunate, compiled code is fine.
