### ISSUE TITLE
Document render-renderable and make-renderable

### ISSUE THREAD

**Issue by duane** [AlexCharlton/glls#3]
`make-renderable` is relatively simple to tease out, but the input format of `render-renderable` is difficult to decipher from the code. It would be nice to have some simple documentation to handle generic glls pipelines.

**Comment by AlexCharlton** [comment]
Thanks for your input! I've restructured the [documentation around renderables](https://github.com/AlexCharlton/glls#renderables), and I'm hopeful that it's now easier figure out how their functions work. Let me know if it's any more clear to you.
