### ISSUE TITLE
examples not working on glsl version 130

### ISSUE THREAD

**Issue by kristianlm** [AlexCharlton/glls#4]
Hey! First, I just wanna say this project (and its friends) is really, really inspiring! I'm really looking forward to some interactive shader development this holiday. You've done an amazing job!

I can't compile with glsl version 330 because computer says no:

```
[klm@kth examples]$ csi -s simple.scm 
Failed to compile shader:

   1|  #version 330
   2|  
   3|  in vec2 position;
   4|  in vec3 color;
   5|  out vec3 c;
   6|  uniform mat4 mvp;
   7|  void main () {
   8|      gl_Position = mvp * vec4(position, 0.0, 1.0);
   9|      c = color;
  10|  }
  11|  

0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES
```

So I add the glsl-version parameter. Then I run into this:

```
[klm@kth examples]$ git diff -U1
diff --git a/examples/simple.scm b/examples/simple.scm
index ef36795..bd76c2b 100644
--- a/examples/simple.scm
+++ b/examples/simple.scm
@@ -40,2 +40,3 @@
 (define model-matrix (mat4-identity))
+(glsl-version 130)
 
[klm@kth examples]$ csi -s simple.scm 
Failed to compile shader:

   1|  #version 130
   2|  
   3|  varying vec3 c;
   4|  varying vec4 fragColor;
   5|  void main () {
   6|      fragColor = vec4(c, 1.0);
   7|  }
   8|  

0:6(2): error: assignment to read-only variable 'fragColor'
```

I don't know if that works for version 330, but I if I apply this patch, it works:

 ```patch
diff --git a/glls-compiler.scm b/glls-compiler.scm
index ecffa3a..5156e82 100644
--- a/glls-compiler.scm
+++ b/glls-compiler.scm
@@ -98,6 +98,8 @@
           (equal? type 'uniform)) type)
      ((and (equal? shader-type #:vertex)
            (equal? type 'in)) 'attribute)
+     ((and (equal? shader-type #:fragment)
+           (equal? type 'out) 'out))
      (else 'varying)))
   (define (params p type)
     (map (lambda (param)
```

1. Is `varying` allowed as both in and out on glsl version 330?
2. If so, which other versions require `out` like 130?
3. Does 330 require `varying` or will this patch work for all glsl versions?

**Comment by kristianlm** [comment]
Hang on! Things are more complicated than that. I see you have [this](https://github.com/AlexCharlton/glls/blob/master/glls-compiler.scm#L95-L101):

```
  (define (in/out-type->glsl-type type)
    (cond
     ((or (>= version 330)
          (equal? type 'uniform)) type)
     ((and (equal? shader-type #:vertex)
           (equal? type 'in)) 'attribute)
     (else type)))
```

I'm new to the non-fixed pipeline in OpenGL, but from my understanding, it's glsl version 130 and up that use in/out instead of attribute/varying. Should that 330 there be 130 and it's fixed once and for all?

**Comment by AlexCharlton** [comment]
Hi, Kristian! Thanks for the kind words :)

You're absolutely right that it should be 130 rather than 330. I see you've fixed it on your branch, so feel free to open a PR :)

**Comment by AlexCharlton** [comment]
Oh, I see your PR already has this fix in it. Cool :)

**Comment by kristianlm** [comment]
The OpenGL world of versions is very confusing! Yeah, it got in the PR by accident ... :)

**Comment by AlexCharlton** [comment]
Yeah, the versions are crazy. 3.3 was promising, as they synced up the shader versions at the same time... but then they had to go and make ES just to complicate things D:
