### ISSUE TITLE
version declaration: saying `#version 300 es` is not possible

### ISSUE THREAD

**Issue by kristianlm** [AlexCharlton/glls#8]
I'd like to use `#version 300 es` for my shaders on my desktop machine. I can't see a way to do this with the current API since version must be an integer.

A sosible solution would be to allow `version: '(300 es)` forms.

**Comment by AlexCharlton** [comment]
Good thinking! I like your solution. PR away!

**Comment by kristianlm** [comment]
Should be in https://github.com/AlexCharlton/glls/pull/7, closing
